require("plugins.plugins-setup")
require("core.options")
require("core.keymaps")

require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.comment")
require("plugins.bufferline")
require("plugins.gitsigns")
require("plugins.telescope")
